### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by revolta** [hustwyk/AndroidSoAddSection#2]
hello,
please can you tell me how to use this code to add a section to .so base in android? i am not a experienced user of java. i would like to add a section to a libil2cpp.so library which is used in many android games today. what exactly sholud i do to use your java code.

any advice would be great. thank you many times.

ps: i wrote you a while age a email, but no answer.

**Comment by revolta** [comment]
yes, i realize that there are included some ".iml" files, they should be from sofware called intellij idea. so i opened the repository in that software. everything seems fine, but the code always gives this error:

```
+++++++++++++++++++Program Header+++++++++++++++++
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.hollybee.addSection.AddSection.parseProgramHeaderList(AddSection.java:380)
	at com.hollybee.addSection.AddSection.parseSo(AddSection.java:255)
	at com.hollybee.addSection.AddSection.main(AddSection.java:48)

Process finished with exit code 1
```

any idead how to fix this? thank you.
